spring:
  application:
    name: "Kontron endpoint tester"
server:
  address: 0.0.0.0
  port: 8080

logging:
  level:
    root: INFO
    com.kontron.endpoint.tester: DEBUG

app:

  cgms:
    base-url: "http://localhost:8590/cgms"
    alarms:
      controller-enabled: true
      controller-path: "/rest/cnms/sbi/vnf/cgms"
      http-enabled: true
      http-path: "/cnms/alarms"
    performance:
      controller-enabled: true
      controller-path: "/rest/cnms/sbi/vnf/cgms"
      http-enabled: true
      http-path: "/cnms/measurements"
    mcptt-security:
      asserted-identity-authorities:
        '[sip:testSystemAdminXUI]': CGMS_ADMIN_PERMISSION
        '[sip:test1]': CGMS_ADMIN_PERMISSION

  kms:
    base-url: "http://localhost:8591/kms"
    alarms:
      controller-enabled: true
      controller-path: "/rest/cnms/sbi/vnf/kms"
      http-enabled: true
      http-path: "/cnms/alarms"
    performance:
      controller-enabled: true
      controller-path: "/rest/cnms/sbi/vnf/kms"
      http-enabled: true
      http-path: "/cnms/measurements"
    mcptt-security:
      asserted-identity-authorities:
        '[sip:testSystemAdminXUI]': KMS_AUD_ADMIN_PERMISSION
        '[sip:test1]': KMS_AUD_ADMIN_PERMISSION